// Code generated by 'go run ./gen'; DO NOT EDIT
package cmd

import (
	"fmt"
	"time"

	"github.com/spf13/cobra"
	
	"github.com/AislingHeanue/Advent-Of-Code/2023/core/day1"
	"github.com/AislingHeanue/Advent-Of-Code/2023/core/day2"
	"github.com/AislingHeanue/Advent-Of-Code/2023/core/day3"
	"github.com/AislingHeanue/Advent-Of-Code/2023/core/day4"
	"github.com/AislingHeanue/Advent-Of-Code/2023/core/day5"
	"github.com/AislingHeanue/Advent-Of-Code/2023/core/day6"
	"github.com/AislingHeanue/Advent-Of-Code/2023/core/day7"
	"github.com/AislingHeanue/Advent-Of-Code/2023/core/day8"
	"github.com/AislingHeanue/Advent-Of-Code/2023/core/day9"
	"github.com/AislingHeanue/Advent-Of-Code/2023/core/day10"
	"github.com/AislingHeanue/Advent-Of-Code/2023/core/day11"
	"github.com/AislingHeanue/Advent-Of-Code/2023/core/day12"
	"github.com/AislingHeanue/Advent-Of-Code/2023/core/day13"
	"github.com/AislingHeanue/Advent-Of-Code/2023/core/day14"
	"github.com/AislingHeanue/Advent-Of-Code/2023/core/day15"
	"github.com/AislingHeanue/Advent-Of-Code/2023/core/day16"
	"github.com/AislingHeanue/Advent-Of-Code/2023/core/day17"
	"github.com/AislingHeanue/Advent-Of-Code/2023/core/day18"
	"github.com/AislingHeanue/Advent-Of-Code/2023/core/day19"
	"github.com/AislingHeanue/Advent-Of-Code/2023/core/day20"
	"github.com/AislingHeanue/Advent-Of-Code/2023/core/day21"
	"github.com/AislingHeanue/Advent-Of-Code/2023/core/day22"
	"github.com/AislingHeanue/Advent-Of-Code/2023/core/day23"
	"github.com/AislingHeanue/Advent-Of-Code/2023/core/day24"
	"github.com/AislingHeanue/Advent-Of-Code/2023/core/day25"
)
	

func addDays(root *cobra.Command) {
	day1.AddCommandsTo(root)
	day2.AddCommandsTo(root)
	day3.AddCommandsTo(root)
	day4.AddCommandsTo(root)
	day5.AddCommandsTo(root)
	day6.AddCommandsTo(root)
	day7.AddCommandsTo(root)
	day8.AddCommandsTo(root)
	day9.AddCommandsTo(root)
	day10.AddCommandsTo(root)
	day11.AddCommandsTo(root)
	day12.AddCommandsTo(root)
	day13.AddCommandsTo(root)
	day14.AddCommandsTo(root)
	day15.AddCommandsTo(root)
	day16.AddCommandsTo(root)
	day17.AddCommandsTo(root)
	day18.AddCommandsTo(root)
	day19.AddCommandsTo(root)
	day20.AddCommandsTo(root)
	day21.AddCommandsTo(root)
	day22.AddCommandsTo(root)
	day23.AddCommandsTo(root)
	day24.AddCommandsTo(root)
	day25.AddCommandsTo(root)
}


func CreateCommand() *cobra.Command {
	var startTime time.Time

	root := &cobra.Command{
		Use:     "aoc",
		Short:   "Advent of Code 2023",
		Long:    "Go implementation of my solutions for the 2023 Advent of Code",
		Example: "go run main.go 1a",
		Args:    cobra.ExactArgs(1),
		PersistentPreRun: func(_ *cobra.Command, _ []string) {
			startTime = time.Now()
		},
		PersistentPostRun: func(_ *cobra.Command, _ []string) {
			fmt.Printf("Time: %v\n", time.Since(startTime))
		},
	}

	addDays(root)

	return root
}
